export type StoreLink = { label: string; href: string };
export type Project = { slug: string; name: string; kind: string; summary: string; image?: string; stack: string[]; role: string; features: string[]; accent: string; storeLinks?: StoreLink[] };

export const projects: Project[] = [
  { slug: 'al-hdeed', name: 'Al Hdeed', kind: 'Saudi construction marketplace', summary: 'A full-stack marketplace for steel and construction materials, combining mobile commerce, operations software, payments, and applied AI.', image: '/assets/Mockups/al_hdeed.png', stack: ['Flutter', 'Next.js', 'Laravel', 'Moyasar', 'AI integrations'], role: 'Mobile, web, backend & AI engineer', features: ['AI voice ordering', 'Drawing-based cost estimation', 'Provider and admin dashboards', 'Secure online payments'], accent: '#f0b56b', storeLinks: [{ label: 'Google Play', href: 'https://play.google.com/store/apps/details?id=com.alhdeed.hdeed&pcampaignid=web_share' }, { label: 'App Store', href: 'https://apps.apple.com/eg/app/%D8%A7%D9%84%D8%AD%D8%AF%D9%8A%D8%AF/id6753888001' }] },
  { slug: 'al-alfy', name: 'Al Alfy', kind: 'Real-time transportation platform', summary: 'A ride booking and intercity travel experience with live vehicle tracking and dependable trip operations.', image: '/assets/Mockups/al_alfy_1.webp', stack: ['Flutter', 'Node.js', 'Socket.IO', 'Google Maps'], role: 'Mobile engineer', features: ['Live tracking', 'Trip management', 'Push notifications', 'Maps and ETA'], accent: '#81e6d9', storeLinks: [{ label: 'Google Play', href: 'https://play.google.com/store/apps/details?id=com.absai.alalphyclient' }, { label: 'App Store', href: 'https://apps.apple.com/eg/app/al-alfy/id6748546309' }] },
  { slug: 'whale-tail-academy', name: 'Whale Tail Academy', kind: 'Education & booking platform', summary: 'A family-facing academy app that makes registration, attendance, schedules, and progress clear and accessible.', image: '/assets/Mockups/whailTail_2.webp', stack: ['Flutter', 'Firebase', 'Cloud Messaging'], role: 'Flutter engineer', features: ['Student registration', 'Progress reporting', 'Attendance', 'Arabic and English'], accent: '#8ba7ff', storeLinks: [{ label: 'Google Play', href: 'https://play.google.com/store/apps/details?id=com.absai.whaletailacademy' }, { label: 'App Store', href: 'https://apps.apple.com/eg/app/whale-tail/id6743503219' }] },
  { slug: 'school-finder', name: 'School Finder', kind: 'School discovery platform', summary: 'A discovery product that helps parents search, compare, and contact nearby schools using live location data.', image: '/assets/Mockups/school_finder_4.webp', stack: ['Flutter', 'REST APIs', 'Google Maps', 'Paymob'], role: 'Mobile engineer', features: ['Location search', 'School comparison', 'Live data', 'Directions'], accent: '#dca5ff', storeLinks: [{ label: 'Google Play', href: 'https://play.google.com/store/apps/details?id=com.absai.school_finder' }, { label: 'App Store', href: 'https://apps.apple.com/us/app/school-finder/id6752694812' }] },
  { slug: 'al-hdeed-provider', name: 'Al Hdeed Provider', kind: 'Provider operations app', summary: 'A companion mobile experience for construction-material providers to manage inventory, orders, and marketplace operations.', stack: ['Flutter', 'Laravel', 'REST APIs'], role: 'Mobile & backend engineer', features: ['Order management', 'Inventory operations', 'Provider workflows', 'Marketplace updates'], accent: '#f0b56b' },
  { slug: 'al-hdeed-landing-page', name: 'Al Hdeed Landing Page', kind: 'Product marketing website', summary: 'A public-facing website introducing the Al Hdeed marketplace and its construction-material purchasing experience.', stack: ['Next.js', 'React', 'Responsive UI'], role: 'Web developer', features: ['Product messaging', 'Responsive design', 'Lead generation', 'Marketplace overview'], accent: '#f0b56b' },
  { slug: 'al-hdeed-web-app', name: 'Al Hdeed Web App', kind: 'Construction marketplace web app', summary: 'A web application supporting the Al Hdeed marketplace, backed by integrated services and REST APIs.', stack: ['Next.js', 'Laravel', 'REST APIs'], role: 'Full-stack engineer', features: ['Marketplace flows', 'Web ordering', 'API integration', 'Responsive interface'], accent: '#f0b56b' },
  { slug: 'al-hdeed-admin-dashboard', name: 'Al Hdeed Admin Dashboard', kind: 'Marketplace operations dashboard', summary: 'An internal dashboard for monitoring marketplace activity and supporting day-to-day administrative operations.', stack: ['Next.js', 'Laravel', 'REST APIs'], role: 'Full-stack engineer', features: ['Operational oversight', 'Order administration', 'Data management', 'Role-based workflows'], accent: '#f0b56b' },
  { slug: 'al-hdeed-provider-dashboard', name: 'Al Hdeed Provider Dashboard', kind: 'Provider management dashboard', summary: 'A dedicated dashboard that gives construction-material providers a clear view of orders and operations.', stack: ['Next.js', 'Laravel', 'REST APIs'], role: 'Full-stack engineer', features: ['Provider analytics', 'Order processing', 'Inventory visibility', 'Account management'], accent: '#f0b56b' },
  { slug: 'whale-tail-dashboard', name: 'Whale Tail Dashboard', kind: 'Academy management dashboard', summary: 'An administration dashboard for coordinating schedules, attendance, announcements, and swimmer progress.', stack: ['Flutter Web', 'Firebase', 'Cloud Messaging'], role: 'Flutter engineer', features: ['Schedule management', 'Attendance tracking', 'Announcements', 'Progress analytics'], accent: '#8ba7ff' },
  { slug: 'al-alfy-driver', name: 'Al Alfy Driver', kind: 'Driver operations app', summary: 'A driver-facing companion app for managing trip availability, live tracking, and ride operations.', image: '/assets/Mockups/alalfy_driver_1.webp', stack: ['Flutter', 'Socket.IO', 'Google Maps'], role: 'Mobile engineer', features: ['Trip requests', 'Live location', 'Driver availability', 'Navigation support'], accent: '#81e6d9', storeLinks: [{ label: 'Google Play', href: 'https://play.google.com/store/apps/details?id=com.absai.al_alfy_driver' }, { label: 'App Store', href: 'https://apps.apple.com/pt/app/al-alfy-driver/id6748659769' }] },
  { slug: 'match-egypt', name: 'Match Egypt', kind: 'Food delivery platform', summary: 'A real-time platform that connects restaurants and delivery drivers to coordinate orders across Egypt.', image: '/assets/Mockups/match_egypt_1.webp', stack: ['Flutter', 'Firebase', 'Google Maps'], role: 'Flutter engineer', features: ['Restaurant discovery', 'Order tracking', 'Location services', 'Push notifications'], accent: '#ffb38a', storeLinks: [{ label: 'Google Play', href: 'https://play.google.com/store/apps/details?id=com.absai.matchdriver' }, { label: 'App Store', href: 'https://apps.apple.com/eg/app/match-egypt/id6743946332' }] },
  { slug: 'match-egypt-restaurant', name: 'Match Egypt Restaurant', kind: 'Restaurant operations app', summary: 'A restaurant companion app for receiving, coordinating, and updating food delivery orders.', image: '/assets/Mockups/match_egypt_2.webp', stack: ['Flutter', 'REST APIs', 'Firebase'], role: 'Flutter engineer', features: ['Order coordination', 'Status updates', 'Restaurant operations', 'Delivery workflow'], accent: '#ffb38a', storeLinks: [{ label: 'Google Play', href: 'https://play.google.com/store/apps/details?id=com.absai.MatchEgyptRest' }] },
  { slug: 'el-akaber-app', name: 'El Akaber App', kind: 'Customer mobile app', summary: 'The official El Akaber restaurant app for browsing dishes, placing orders, and tracking deliveries.', image: '/assets/Mockups/elakaber_1.png', stack: ['Flutter', 'REST APIs', 'Firebase'], role: 'Flutter engineer', features: ['Mobile user flows', 'API integration', 'Push notifications', 'Store release'], accent: '#f3cf90', storeLinks: [{ label: 'Google Play', href: 'https://play.google.com/store/apps/details?id=com.absai.sobhikaber_dashboard.prod' }, { label: 'App Store', href: 'https://apps.apple.com/eg/app/el-akaber/id6739861335' }] },
  { slug: 'el-akaber-dashboard', name: 'El Akaber Dashboard', kind: 'Operations dashboard', summary: 'A web dashboard supporting El Akaber’s internal administration and operational workflows.', stack: ['Flutter Web', 'REST APIs', 'Responsive UI'], role: 'Flutter engineer', features: ['Operational workflows', 'Data management', 'Responsive dashboard', 'Administration tools'], accent: '#f3cf90' },
  { slug: 'resaltk-admin', name: 'Resaltk Admin', kind: 'Admin mobile app', summary: 'An administrative application supporting operational workflows for the Resaltk product.', image: '/assets/Mockups/1_resaltk.png', stack: ['Flutter', 'REST APIs', 'Firebase'], role: 'Flutter engineer', features: ['Administrative workflows', 'Mobile operations', 'Data updates', 'Store release'], accent: '#ff9ebb' },
  { slug: 'mazaq-al-lahim', name: 'Mazaq Al Lahim', kind: 'Food ordering app', summary: 'A customer-facing food product with integrated mobile ordering and production-ready release workflows.', image: '/assets/Mockups/1_lahim.png', stack: ['Flutter', 'REST APIs', 'Firebase'], role: 'Flutter engineer', features: ['Food ordering', 'Mobile checkout', 'Push notifications', 'Store release'], accent: '#e69a72', storeLinks: [{ label: 'Google Play', href: 'https://play.google.com/store/apps/details?id=com.absai.mazakallahem' }, { label: 'App Store', href: 'https://apps.apple.com/sa/app/mazaq-al-lahim/id6755496808' }] },
  { slug: 'amazon-product-browse-node-classification', name: 'Amazon Product Browse Node Classification', kind: 'Machine learning project', summary: 'A classification model for assigning Amazon products to the correct browse-node categories.', stack: ['Python', 'TensorFlow', 'Scikit-learn'], role: 'Machine learning engineer', features: ['Data preprocessing', 'Feature engineering', 'Classification', 'Model evaluation'], accent: '#b6fff0' },
  { slug: 'drug-recommendation-system', name: 'Drug Recommendation System', kind: 'Deep learning project', summary: 'A deep-learning system designed to support medicine recommendations from relevant input data.', stack: ['Python', 'TensorFlow', 'Deep Learning'], role: 'Machine learning engineer', features: ['Data processing', 'Neural networks', 'Recommendation logic', 'Evaluation'], accent: '#b6fff0' },
  { slug: 'qa-chatbot-rag', name: 'Q&A Chatbot with RAG', kind: 'LLM application', summary: 'A retrieval-augmented question-answering chatbot that combines document context with an LLM response layer.', stack: ['Python', 'LLMs', 'RAG', 'Vector Search'], role: 'AI engineer', features: ['Document retrieval', 'Vector search', 'Contextual answers', 'LLM orchestration'], accent: '#b6fff0' },
  { slug: 'ai-text-detection', name: 'AI-Generated Text Detection', kind: 'Neural network project', summary: 'A neural-network approach for detecting whether written content was generated by AI.', stack: ['Python', 'TensorFlow', 'NLP'], role: 'Machine learning engineer', features: ['Text preprocessing', 'Neural networks', 'Classification', 'Model evaluation'], accent: '#b6fff0' },
  { slug: 'arabic-customer-review-classification', name: 'Arabic Customer Review Classification', kind: 'NLP project', summary: 'An NLP classification project for extracting signal from Arabic customer reviews.', stack: ['Python', 'NLP', 'TensorFlow'], role: 'Machine learning engineer', features: ['Arabic text processing', 'Sentiment classification', 'Data preparation', 'Evaluation'], accent: '#b6fff0' },
  { slug: 'corporate-bankruptcy-prediction', name: 'Corporate Bankruptcy Prediction', kind: 'Predictive analytics project', summary: 'A predictive model for assessing corporate bankruptcy risk from financial data.', stack: ['Python', 'Scikit-learn', 'Data Analysis'], role: 'Machine learning engineer', features: ['Financial data processing', 'Risk prediction', 'Feature selection', 'Model evaluation'], accent: '#b6fff0' },
  { slug: 'bank-debit-collection-analysis', name: 'Bank Debit Collection Analysis', kind: 'Data analysis project', summary: 'An analysis project focused on understanding bank debit-collection performance and trends.', stack: ['Python', 'Data Analysis', 'Visualization'], role: 'Data analyst', features: ['Data cleaning', 'Trend analysis', 'Performance insights', 'Reporting'], accent: '#b6fff0' }
];

export const experience = [
  { date: 'May 2026 — Present', company: 'Alfiya United Company', role: 'Mobile & Web Developer · Backend · AI Integrations', location: 'Jeddah, Saudi Arabia · On-site', body: 'Building Al Hdeed across Flutter, web, Laravel APIs, payments, and AI-assisted ordering and construction estimation.', stack: 'Flutter · Next.js · Laravel · Moyasar · LLMs' },
  { date: 'Aug 2024 — Apr 2026', company: 'ABS.AI Technologies', role: 'Flutter Developer', location: 'Cairo, Egypt · Hybrid', body: 'Shipped scalable applications with real-time tracking, maps, payments, analytics, robust networking, and store releases.', stack: 'Flutter · Firebase · Google Maps · Paymob · GitHub Actions' },
  { date: 'Jul 2023 — Nov 2023', company: 'TechnoColab Inc.', role: 'Machine Learning Intern', location: 'Remote · India', body: 'Built predictive models and data pipelines, from preprocessing and feature selection through evaluation.', stack: 'Python · TensorFlow · Scikit-learn' }
];
